### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by MX10-AC2N** [SamLangTen/KaraokeShow#21]
I am trying to use KaraokaShow with the very latest version of MusicBee, the plugin is correctly installed, I can activate the plugin via the display settings but I only have an empty rectangle that appears that I can move anywhere I want on The MusicBee window but no song lyrics displayed.
How do you use the plugin ? Why don't I have any lyrics via the plugin when if I activate the lyrics in the MusicBee settings I have the lyrics of my songs.
There are probably a few things that I didn't understand.
Thanks in advance..

**Comment by tdemin** [comment]
@MX10-AC2N are you sure you're using LRC lyrics, and not the ones stored in unsynchronized lyrics tags? The README explicitly states KaraokeShow doesn't support unsynchronized lyrics.

**Comment by MX10-AC2N** [comment]
Thanks @tdemin In fact I don't have LRC Lyrics, I don't know how MusicBee can recieve this LRC Lyrics.. So finally I have try "MiniLyrics" and that's ok

**Comment by SamLangTen** [comment]
@MX10-AC2N 
You need to have some plugins for synchronized lyrics retrieval installed.
Here are some plugins I have used, which can retrieve synchronized lyrics from some online music streaming services. These some online music streaming serivces are served for Chinese users but there are also a lot of non-Chinese lyrics:
* [MusicBee-NeteaseLyrics](https://github.com/cqjjjzr/MusicBee-NeteaseLyrics)
* [getLyrics-QQMusic](https://github.com/Dixeran/getLyrics)

If you have downloaded or created a LRC file, you can rename it the same as music file. MusicBee may automatically read your LRC file so that KaraokeShow can parse and paint it. Bacause MusicBee's lyrics loading for local file system is too simple, I have made another [plugin](https://github.com/SamLangTen/MusicBeeLocalLyricsLoader) to enhance it.
